models/Dom.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "dom".
 *
 * @property integer $id
 * @property string $tech_data
 * @property string $text
 * @property string $avatarId
 */
class Dom extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dom';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['text','active','tech_data', 'avatarId','sales'], 'required'],
            [['text','price','material_house','material_roof','material_windows','material_doors','material_wall','area','eart','address','dop_info','post_adress','readiness','poverh'], 'string'],
            [['tech_data', 'avatarId'], 'string', 'max' => 1000],
            [['geo_lat', 'geo_lng'], 'string', 'max' => 45],
            [['active','sales','promo'],'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tech_data' => 'Подробное описание',
            'text' => 'Текст',
            'avatarId' => 'Фото ID',
            'price' => 'Стоимость',
            'material_house' => 'Материал стен',
            'material_roof' => 'Материал крыши',
            'material_windows' => 'Материал окон',
            'material_doors' => 'Материал дверей',
            'material_wall' => 'Материал внутр стен',
            'area' => 'Площадь дома',
            'eart' => 'Земельный участок',
            'address' => 'Короткий адрес',
            'dop_info' => 'Дополнительная информация(для главной стр)',
            'geo_lat' => 'Координата 1',
            'geo_lng' => 'Координата 2',
            'post_adress' => 'Почтовый адрес',
            'readiness' => 'Готовность',
            'poverh' => 'Этажей',
            'active' => 'Активна',
        ];
    }


    public function getAvatar()
    {
        return $this->hasOne(DomImages::className(), ['id' => 'avatarId']);
    }
    public function getVideo()
    {
        return $this->hasMany(Video::className(), ['idDom' => 'id']);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Dom;
use app\models\DomImagesSearch;
use app\models\SignupForm;
use app\models\DomSearch;
use app\models\News;
use app\models\NewsSearch;
use app\models\Panorama;
use app\models\Promo;
use app\models\UserInfo;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\TagSearch;




class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['login', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            $role = key(Yii::$app->authManager->getRolesByUser(Yii::$app->user->id));
            if ($role == 'admin') {
                return $this->redirect(['admin/index']);
            }
            return true;
        }
        return false;
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
//            'captcha' => [
//                'class' => 'yii\captcha\CaptchaAction',
//                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
//            ],

        ];

    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $promoSearch = new Promo();
        $promo = $promoSearch->getPromo();
        $searchModel = new DomSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'promo' => $promo,
            'model' => new UserInfo(),
        ]);

    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        $this->redirect(['admin/login']);
    }

    public function actionMore($id)
    {
        $promoSearch = new Promo();
        $promo = $promoSearch->getPromo();
        $dom = Dom::findOne($id);
        $searchModel = new DomImagesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $id,$dom->avatarId);
//        printr_r($promo);die();
        return $this->render('more', [
            'dom' => $dom,
            'promo' => $promo,
            'images' => $dataProvider,
            'model' => new UserInfo(),
        ]);
    }

    /*3d tour*/
    public function actionPanorama($id)
    {
        $dom = Dom::findOne($id);
        $panorama = Panorama::find()->where(['idDom'=> $id,'status_id'=>2])->all();
        return $this->render('panorama', [
            'dom' => $dom,
            'images' => $panorama,
            'model' => new UserInfo(),
        ]);
    }
    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new UserInfo();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $message = $model->name.' оставил заявку на тему '.$model->subject.'. Текст сообщения: '.$model->text.'. Мои контакты телефон: '.$model->telefone.' , email: '.$model->email.'.';
            Yii::$app->session->setFlash('success', 'Сообщение отправлено. В ближайшее время мы ответим Вам.');
            Yii::$app->mailer->compose()
                ->setTo('synytsina@mail.ru')
                ->setFrom('to@domsovinyon.com')
                ->setSubject('Тема сообщения')
                ->setTextBody('Текст сообщения')
                ->setHtmlBody($message)
                ->send();
            return $this->refresh();
        }else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about',[
            'model' => new UserInfo(),
        ]);

    }

    public function actionCallme($type)
    {
        $model = new UserInfo();
        switch($type){
            case 1: $render = '_callme';break;
            case 2: $render = 'callme';break;
        }

        if($model->load(Yii::$app->request->post()) && $model->save() ) {
            $message = $model->name.' оставил заявку.Пожалуйста свяжитесь со мной по телефону'.$model->telefone;
            $success = true;
            Yii::$app->mailer->compose()
                ->setTo('konrun@mail.ru')
                ->setFrom('to@domsovinyon.com')
                ->setSubject('Тема сообщения')
                ->setTextBody('Текст сообщения')
                ->setHtmlBody($message)
                ->send();
            return json_encode($success);
        }

        return $this->renderPartial($render, [
            'model' => $model,
        ]);


    }
    public function actionProject()
    {
        return $this->render('project',[
            'model' => new UserInfo(),
        ]);
    }
    public function actionMaterial()
    {
        return $this->render('material',[
            'model' => new UserInfo(),
        ]);

    }

    public function actionTehnology()
    {
        return $this->render('tehnology',[
            'model' => new UserInfo(),
        ]);

    }

    public function actionDocumenty()
    {
        return $this->render('documenty',[
            'model' => new UserInfo(),
        ]);
    }
    public function actionNews()
    {
        $category = Category::find()->all() ;
        $searchModelTag = new TagSearch();
        $dataProviderTag = $searchModelTag->search(Yii::$app->request->queryParams);
        $searchModel = new NewsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProviderLast = $searchModel->search(Yii::$app->request->queryParams,1);
        return $this->render('news',[
            'model' => new UserInfo(),
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'category' => $category,
            'dataProviderLast' => $dataProviderLast,
            'dataProviderTag' => $dataProviderTag,
        ]);
    }

    public function actionCallmePopup()
    {
        $model = new SignupForm();
        return $this->renderPartial('signup', [
            'model' => $model,
        ]);
    }

    public function actionNewsMore ($id) {
        $searchModelTag = new TagSearch();
        $dataProviderTag = $searchModelTag->search(Yii::$app->request->queryParams);
        $category = Category::find()->all() ;
        $searchModel = new NewsSearch();
        $dataProviderLast = $searchModel->search(Yii::$app->request->queryParams,1);
        $model = new News();
        $news = $model->findOne($id) ;
        return $this->render('news-more', [
            'news' => $news,
            'model' => new UserInfo(),
            'category' => $category,
            'dataProviderLast' => $dataProviderLast,
            'dataProviderTag' => $dataProviderTag,
        ]);

    }

// Всплывшее модальное окно заполняем представлением signup.php формы с полями
    public function actionSignup()
    {
        $model = new SignupForm();
        //$model->id =$userid;
        return $this->renderPartial('callme', [
            'model' => $model,
        ]);
    }

// По нажатию в модальном окне на Отправить - форма отправляется администратору на почту
    public function actionSubmitsignup()
    {
        $model = new SignupForm();
        $model->load(Yii::$app->request->post());

        if($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {

            //save the password
            $success=true;
            return json_encode($success);
        }
        else
        {
            return $this->renderPartial('signup', [
                'model' => $model,
            ]);
        }
    }

}

views/site/_news_list.php
<?php

?>


<div class="col-md-4 col-sm-4">
    <a href="<?=\yii\helpers\Url::toRoute(['site/news-more','id'=> $model->id]) ?>">
        <img src="/img/news/<?= $model->id?>/cropped/<?= $model->avatar?>" class="img-responsive center-block img-padder" alt="<?= $model->title?>" title="<?= $model->title?>">
    </a>
</div>

<div class="col-md-8 col-sm-8">
    <h4 datetime="<?= date('d.m.Y', $model->datetime); ?>">
        <a href="<?=\yii\helpers\Url::toRoute(['site/news-more','id'=> $model->id]) ?>">
            <?= $model->title?>
        </a>
    </h4>
    <ul class="list-inline info">
        <li><i class="fa fa-user-md"></i> Администратор</li>
        <li><i class="fa fa-calendar"></i> <?= date('d.m.Y', $model->datetime); ?></li>
        <li><i class="fa fa-tag"></i> <a href="#"> <?= $model->category->title ?></a></li>
    </ul>

    <p>
        <?= Yii::$app->DLL->subStr($model->text, 400) ?>
    </p>
    <p>
        <a href="<?=\yii\helpers\Url::toRoute(['site/news-more','id'=> $model->id]) ?>" class="btn big-link-1">Продолжить чтение</a>
    </p>

</div>

views/site/_video.php
<?php

?>


<?php foreach($dom->video as $video):  ?>
    <?php if($video->status_id==2){ ?>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 video">
            <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" src="<?=$video->link?>"></iframe>
            </div>
            <div class = "caption"> <h3><?=$video->name_video?></h3></div>
        </div>
    <?php } ?>
<?php endforeach; ?>

views/site/_view.php
<?php

use yii\helpers\Url;
use app\models\DomImages;
use app\models\Panorama;
use app\models\Promo;
?>

<?php $avatar = DomImages::findOne($model->avatarId);

?>
<div class="work wow fadeInDown">
    <div class="box1">

        <a class="view-work" href="<?= Yii::getAlias('@web') .'/img/dom/' .$model->id .'/cropped/p_'.$avatar->path?>">
            <?php if($model->sales ==2){
                $sales= '';
            }else  $sales= 'sales';
            ?>
            <div class="lenta-wrapper-yellow <?=$sales?>"><div class="lenta-yellow">ПРОДАНО</div></div>
            <?php $infos=Promo::find()->where(['status'=>1,'id_dom'=>$model->id])->one();
            if($infos['status']==1) :?>
<!--                <div class="lenta-action"><img class="image-2" alt="Изображение пометки акция" src="--><?//= Yii::getAlias('@web') .'/img/promo/'.$infos['ugol_photo']?><!--"></div>-->
            <?php endif;?>
            <img class="image-2" alt="Изображение дома по адресу <?= $model->address?>" src="<?= Yii::getAlias('@web') .'/img/dom/' .$model->id .'/cropped/'.$avatar->path?>"></a>
        <?php if(!empty($model->price)) :?>
            <h3><?= $model->price?></h3>
        <?php else:?>
            <p class="balkon"></p>
        <?php endif ?>
        <h4 class="view-info-adress"><?= $model->address?></h4>
    </div>
    <div class="pricing-1-box-features">
        <ul>
            <li><span class = "pull-left">&nbsp;&nbsp;<i class = "glyphicon glyphicon-home color-price"></i></span><b><?= $model->area?> м<sup>2</sup></b></li>
            <li><span class = "pull-left">&nbsp;&nbsp;<i class = "glyphicon glyphicon-picture color-price"></i></span><b><?= $model->eart?></b></li>
            <li><span class = "pull-left">&nbsp;&nbsp;<i class = "glyphicon glyphicon-info-sign color-price"></i></span><b>&nbsp;&nbsp;<?= $model->dop_info?></b></li>
        </ul>
    </div>
    <div class="work-bottom">
        <a class="btn-sm big-link-1" href="<?= Url::toRoute(['site/more','id'=>$model->id])?>">ПОДРОБНЕЕ</a>
        <?php $panorama = Panorama::find()->where(['idDom'=>$model->id,'status_id'=>2])->one(); ?>

        <?php if (!empty($panorama)) {?>
            <a class="btn-sm big-link-1" href="<?= Url::toRoute(['site/panorama','id'=>$model->id])?>">3D ТУР &nbsp;<i class="fa fa-eye"></i></a>
        <?php }?>
    </div>
</div>

views/site/_view_gallery.php
<?php ?>

        <a class="thumbnail view-work" href="<?= Yii::getAlias('@web')  .'/img/'.$model->idDom.'/' . $model->path?>" title="foto">
            <img class="image" alt="foto" src="<?= Yii::getAlias('@web')  .'/img/'.$model->idDom.'/' . $model->path?>"><a>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
$this->registerMetaTag(['name' => 'keywords', 'content' => 'DOM SOVINYON,лучшие дома в районе Совиньон,контакты']);
$this->registerMetaTag(['name' => 'description', 'content' => 'DOM SOVINYON - продажа домов в элитном районе Одессы'], 'description');
$this->title = 'Контакты';

$this->params['breadcrumbs'][] = $this->title;
?>
<section id="contacty">
    <div class="page-title-container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 wow fadeIn">
                    <i class="fa fa-envelope"></i>
                    <h1>Свяжитесь с нами / </h1>
                    <p>Здесь вы можете связаться с нами</p>
                </div>
            </div>
        </div>
    </div>

    <div class="contact-us-container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 box2">
                    <div class="col-lg-7 col-md-7 col-sm-6 col-xs-12 contact-form wow fadeInLeft">
                        <p>
                            Если у Вас возникли вопросы и предложения, можете связаться с нами, заполнив простую форму связи или любым удобным способом указанным в контактах.
                        </p>
                            <?php if (Yii::$app->session->hasFlash('success')): ?>
                            <div class="alert">
                                <h2 class="text-center"><span class="violet">Спасибо за обращение к нам.<br> Мы постараемся ответить вам как можно скорее.</span></h2>
                            </div>
                        </div>
                        <?php else: ?>
                            <?php $form = ActiveForm::begin(['id' => 'contact-form']);?>
                            <div class="form-group">
                                <?= $form->field($model, 'name')->textInput(['placeholder' => 'Как можно к Вам обращаться?'])?>
                            </div>
                            <div class="form-group">
                                <?= $form->field($model, 'email')?>
                            </div>
                            <div class="form-group">
                                <?= $form->field($model, 'subject')?>
                            </div>
                            <div class="form-group">
                                <?= $form->field($model, 'telefone')->widget(\yii\widgets\MaskedInput::className(), [
                                    'mask' => '+8 (999) 999 99 99',
                                ]);?>
                            </div>
                            <div class="form-group">
                                <?= $form->field($model, 'text')->textArea(['rows' => 6])?>
                            </div>
                            <?= Html::submitButton('Отправить', ['class' => 'btn', 'name' => 'contact-button'])?>
                            <?php ActiveForm::end();?>
                        <?php endif; ?>
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12 wow fadeInUp">
                        <div class="thumbnail not-border">
                            <img class="img-responsive" src="/img/table-send.png">
                        </div>
                        <h2 class="black">НАШИ КОНТАКТЫ</h2>
                        <p class="text-uppercase"><i class="fa fa-phone fa-3x color-price"></i>&nbsp;&nbsp;&nbsp;<b class="contact-size color-price"> +38 (067) 654 25 64</b></p>
                        <p class="text-uppercase"><i class="fa fa-envelope fa-2x color-price"></i><em class="contact-size2 color-price">&nbsp;&nbsp;&nbsp;sales@domsovinyon.com</em></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = '(#404)';
?>


<section id="contacty">
    <div class="page-title-container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 wow fadeIn">
                    <i class="fa fa-warning"></i>
                    <h1>(#404) / </h1>
                    <p>Страница не найдена на сайте www.domsovinyon.com</p>
                </div>
            </div>
        </div>
    </div>

    <div class="contact-us-container">
        <div class="container">
            <div class="row box2">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="col-lg-7 col-md-7 col-sm-6 col-xs-12 contact-form wow fadeInLeft">
                        <h3 class="text-uppercase">Страница по указанному в браузера адресу не существует. </h3>
                        <p>Для дальнейшего просмотра сайта пожалуйста перейдите на страницу указанную в главном меню. </p>

                        <div class="thumbnail not-border">
                            <img class="" src="/img/404.png">
                        </div>
                        <p>В случае возникновения дополнительных вопросов Вы можете обратиться к нам по указанным контактам. </p>
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12 wow fadeInUp">
                        <div class="thumbnail not-border">
                            <img class="" src="/img/table-send.png">
                        </div>
                        <h2 class="black">НАШИ КОНТАКТЫ</h2>
                        <p class="text-uppercase"><i class="fa fa-phone fa-3x color-price"></i>&nbsp;&nbsp;&nbsp;<b class="contact-size color-price"> +38 (067) 654 25 64</b></p>
                        <p class="text-uppercase"><i class="fa fa-envelope fa-2x color-price"></i><em class="contact-size2 color-price">&nbsp;&nbsp;&nbsp;sales@domsovinyon.com</em></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

views/site/index.php
<?php

use yii\widgets\ListView;

/* @var $this yii\web\View */


$this->registerMetaTag(['name' => 'keywords', 'content' => 'DOM SOVINYON,лучшие дома в районе Совиньон']);
$this->registerMetaTag(['name' => 'description', 'content' => 'DOM SOVINYON - продажа домов в элитном районе Одессы, низкие цены дома, котеджиб дома с участком,готовые дома'], 'description');
$this->title = 'DOM SOVINYON | Главная страница';

?>
<section id="home">

    <div class="presentation-container">
        <?php if (!empty($promo) && $promo[0]['slider_home'] == 1) :?>
            <?= $this->render('/layouts/_slider') ?><br><br>
        <?php endif;?>
        <?php if(!empty($promo)) :?>
            <?php
            $data_starta = $promo[0]['promo_date'];
            ?>
            <?php  $script = <<< JS
$('#countdown').timeTo({
    timeTo: new Date(new Date('Mon May 01 2017 09:00:00 GMT+0200 (Финляндия (зима))')),
    displayDays: 2,
    theme: "black",
    displayCaptions: true,
    fontSize: 48,
    captionSize: 14
}); 
JS;
            $this->registerJs($script, yii\web\View::POS_READY); ?>
            <div class="container">
            <div class="row">
                <?= $this->render('promo-block') ?>
            </div>
        <?php else: ?>
            </div>
            <?= $this->render('/layouts/_slider') ?>
        <?php endif;?>

    </div>
    <div class="presentation-container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 wow fadeInLeftBig box2">
                    <h1><span class="violet">DOM SOVINYON </span> - строительство и продажа домов в элитном районе Одессы</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="work-container">
        <div class="container">

            <?= ListView::widget([
                'dataProvider' => $dataProvider,
                'itemView' => '_view',
                'options' => ['class' => 'col-lg-12 col-md-12 col-sm-12 col-xs-12'],
//                    'layout' => "{items}<div class=\"clear\"></div>{pager}",
                'emptyText' => 'Список пуст',
                'summary' => false,
                'itemOptions' => [
                    'tag' => 'div',
                    'class' => 'col-lg-4 col-md-4 col-sm-6 col-xs-12',
                ],
            ]) ?>

        </div>
    </div>
</section>
<?= $this->render('/layouts/_company') ?>
<div class="container">
    <div class="row">
        <?= $this->render('_callme', ['model' => $model]) ?>
    </div>
</div><br><br>

views/site/moremaps.php
<?php

use dosamigos\google\maps\LatLng;
use dosamigos\google\maps\services\DirectionsWayPoint;
use dosamigos\google\maps\services\TravelMode;
use dosamigos\google\maps\overlays\PolylineOptions;
use dosamigos\google\maps\services\DirectionsRenderer;
use dosamigos\google\maps\services\DirectionsService;
use dosamigos\google\maps\overlays\InfoWindow;
use dosamigos\google\maps\overlays\Marker;
use dosamigos\google\maps\Map;
use dosamigos\google\maps\services\DirectionsRequest;
use dosamigos\google\maps\overlays\Polygon;
use dosamigos\google\maps\layers\BicyclingLayer;

$coord = new LatLng(['lat' => $lat, 'lng' => $lng]);
$map = new Map([
    'center' => $coord,
    'zoom' => 19,
    'width' => '100%',
    'height' => '100%',
]);

// Позволяет добавить маркер в настоящее время
$marker = new Marker([
    'position' => $coord,
    'title' => 'Офис продаж',
]);

// Обеспечить общий InfoWindow к маркеру
$marker->attachInfoWindow(
    new InfoWindow([
        'content' => '<p>Отличный дом для добрых людей!</p>'
    ])
);

// Добавить маркер на карте
$map->addOverlay($marker);

// Отображение карты
echo $map->display();

views/site/panorama.php
<?php


//use yii\helpers\Html;
//$this->registerJsFile('panorama/js/jquery.cyclotron.js');

use app\models\Panorama;

$this->title = 'Виртуальный тур';

?>

<section id="panorama">
    <div class="page-title-container">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 wow fadeIn">
                    <i class="fa fa-camera"></i>
                    <h1><?=$this->params['breadcrumbs'][] = $this->title;?> /</h1>
                    <p>Ниже вы можете найти более подробную информацию о нашей компании</p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="presentation-container">

                <div class="col-sm-12 wow fadeInLeftBig box2">
                    <h1><span class="violet">DOM SOVINYON </span>, предлагаем красивые дома в лушем районе любимой
                        Одессы.</h1>
                    <p>СОВИНЬОН - лучший район для добрых людей и красивых домов.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="about-us-container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 wow fadeIn box2">
                    <ul class="nav nav-tabs">
                        <?php $i=1;
                        foreach ($images as $image):
                            ?>
                            <?php if($i==1){
                            $active = 'active';
                        }else $active= '';
                            ?>
                            <li class="<?=$active?>"><a data-toggle="tab" href="#<?=$i?>">
                                    <p><img src="<?= Yii::getAlias('@web') . '/img/panorama/' . $image->idDom . '/cropped/pm_' . $image->avatar->path ?>"  alt=""  title=""></p>
                                    <h5><?=$image->header_image?></h5>
                                </a></li>
                            <?php $i++; endforeach; ?>
                    </ul>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="tab-content boxShadow9">
                            <?php $j = 1;
                            foreach ($images as $image):
                                ?>
                                <?php if($j==1){
                                $active_in = 'in active';
                            }else $active_in= '';

                                ?>
                                <div id="<?=$j?>" class="tab-pane fade <?=$active_in?>">
                                    <div class="panorama"> <img src="<?= Yii::getAlias('@web') . '/img/panorama/' . $image->idDom . '/cropped/pb_' . $image->avatar->path ?>"  alt=""  title=""></div>
                                    <h3 class="text-center"><?=$image->header_image?></h3>
                                </div>
                                <?php $j++; endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>





</section>
<div class="container">
    <div class="row">
        <?= $this->render('_callme', ['model' => $model]) ?>
    </div>
</div>

views/site/promo-block.php
<?php

use app\models\Promo;
//print_r($promo);die();
$promo = Promo::find()->where(['status'=>1])->all();
?>

    <div class="box2 col-lg-12 col-md-12 col-sm-12 col-xs-12 wow fadeIn"><br>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <img class="image-3 promo" alt="promo image" src="<?= Yii::getAlias('@web') .'/img/promo/' . $promo[0]['promo_photo']?>">

            <div class="work-bottom">  <br>
                <a class="btn-sm big-link-1" href="/site/more/<?=$promo[0]['id_dom']?>">УЗНАТЬ БОЛЬШЕ</a>
                <br>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <h2 class="text-uppercase text-center violet text-promo">Предложение действует:</h2>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <br>
                <div id="countdown"></div>
                <br>
            </div>

    </div>

views/site/signup.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\gbUser $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div id="success"> </div>

<div class="gb-user-form">

    <?php $form = ActiveForm::begin(['options' => ['class' => 'signup-form']]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => 55], ['class' => 'input-modal']) ?>

    <?= $form->field($model, 'phone')->textInput(['maxlength' => 25], ['class' => 'input-modal']) ?>


    <div class="form-group text-right">
        <?= Html::submitButton('Отправить', ['class' => 'btn btn-success btn-update-password']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>