models/Dom.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "dom".
 *
 * @property integer $id
 * @property string $tech_data
 * @property string $text
 * @property string $avatarId
 */
class Dom extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dom';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['text','active','tech_data', 'avatarId','sales'], 'required'],
            [['text','price','material_house','material_roof','material_windows','material_doors','material_wall','area','eart','address','dop_info','post_adress','readiness','poverh'], 'string'],
            [['tech_data', 'avatarId'], 'string', 'max' => 1000],
            [['geo_lat', 'geo_lng'], 'string', 'max' => 45],
            [['active','sales','promo'],'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tech_data' => 'Подробное описание',
            'text' => 'Текст',
            'avatarId' => 'Фото ID',
            'price' => 'Стоимость',
            'material_house' => 'Материал стен',
            'material_roof' => 'Материал крыши',
            'material_windows' => 'Материал окон',
            'material_doors' => 'Материал дверей',
            'material_wall' => 'Материал внутр стен',
            'area' => 'Площадь дома',
            'eart' => 'Земельный участок',
            'address' => 'Короткий адрес',
            'dop_info' => 'Дополнительная информация(для главной стр)',
            'geo_lat' => 'Координата 1',
            'geo_lng' => 'Координата 2',
            'post_adress' => 'Почтовый адрес',
            'readiness' => 'Готовность',
            'poverh' => 'Этажей',
            'active' => 'Активна',
        ];
    }


    public function getAvatar()
    {
        return $this->hasOne(DomImages::className(), ['id' => 'avatarId']);
    }
    public function getVideo()
    {
        return $this->hasMany(Video::className(), ['idDom' => 'id']);
    }
}

controllers/DomController.php
<?php

namespace app\controllers;

use app\models\DomImages;
use app\models\DomImagesSearch;
use app\models\UploadForm;
use Yii;
use app\models\Dom;
use app\models\DomAdminSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * DomController implements the CRUD actions for Dom model.
 */
class DomController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index','view','create','update','delete','image','login','logout'],
                'rules' => [
                    [
                        'actions' => ['index','view','create','update','delete','image','imagemore'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],

                    [
                        'allow' => true,
                        'actions' => ['login'],
                        'roles' => ['?'],
                    ],

                    [
                        'allow' => true,
                        'actions' => ['logout'],
                        'roles' => ['@'],
                    ],

                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            $this->layout = 'admin.php';


            return true;
        }
        return false;
    }

    /**
     * Lists all Dom models.
     * @return mixed
     */
    public function actionIndex()
    {

        $searchModel = new DomAdminSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Dom model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $files = DomImages::find()->where(['idDom' => $model->id])->all();
        $searchModel = new DomImagesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $id,$model->avatarId);
        return $this->render('view', [
            'model' =>   $model,
            'images' => $dataProvider,
            'files' =>$files,
        ]);
    }

    /**
     * Creates a new Dom model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Dom();
        $upload = new UploadForm();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            $upload->avatar($model->id);
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'upload' => $upload,
            ]);
        }
    }

    /**
     * Updates an existing Dom model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $upload = new UploadForm();

        if ($model->load(Yii::$app->request->post()) ) {
            $model->save();
//            print_r($model->getErrors());die();
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            $upload->avatar($model->id);
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'upload' => $upload,
            ]);
        }
    }

    /**
     * Deletes an existing Dom model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Dom model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Dom the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Dom::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


    public function actionImage($id)
    {
        $model = $this->findModel($id);

        $upload = new UploadForm();

        $photos = DomImages::find()->where(['idDom'=> $id])->andWhere('id' != $model->avatarId)->all();

        if ( $model->load(Yii::$app->request->post()) ) {
//            print_r(1);die();
            $upload->files = UploadedFile::getInstances($upload, 'files');
            if (!empty($upload->files)) {
                $upload->photos($model->id);
            }
            $this->redirect(['image','id'=>$id]);
        }

        return $this->render('image', [
            'model' => $model,
            'upload' => $upload,
            'photos' =>$photos,
        ]);
    }


    public function actionImagemore($id)
    {

        $model = $this->findModel($id);
        $searchModel = new DomImagesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$id,$model->avatarId);

        return $this->render('imagemore', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

}

views/dom/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Dom */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="dom-form">

	<div class="box box-default">

		<div class="box-body">
			<div class="row">
				<div class="col-sm-12">
					<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
					<div class="col-sm-6">
						<?= $form->field($model, 'price')->textInput(['maxlength' => true]) ?>
						<?= $form->field($model, 'eart')->textInput(['maxlength' => true]) ?>
						<?= $form->field($model, 'area')->textInput(['maxlength' => true]) ?>

					</div>
					<div class="col-sm-6">
						<?= $form->field($model, 'address')->textInput(['maxlength' => true]) ?>
						<?= $form->field($model, 'post_adress')->textInput(['maxlength' => true]) ?>
						<?= $form->field($model, 'poverh')->textInput(['maxlength' => true]) ?>
					</div>
					<div class="col-sm-6">
						<?= $form->field($model, 'geo_lat')->textInput(['maxlength' => true]) ?>
						<?= $form->field($model, 'readiness')->textInput(['maxlength' => true]) ?>
						<?= $form->field($model, 'material_roof')->textInput(['maxlength' => true]) ?>
					</div>
					<div class="col-sm-6">
						<?= $form->field($model, 'geo_lng')->textInput(['maxlength' => true]) ?>
						<?= $form->field($model, 'material_house')->textInput(['maxlength' => true]) ?>
						<?= $form->field($model, 'material_windows')->textInput(['maxlength' => true]) ?>
					</div>
					<div class="col-sm-6">
						<?= $form->field($model, 'material_doors')->textInput(['maxlength' => true]) ?>
						<?= $form->field($model, 'dop_info')->textarea(['rows' => 2]) ?>
					</div>
					<div class="col-sm-6">
						<?= $form->field($model, 'material_wall')->textInput(['maxlength' => true]) ?>
						<?= $form->field($model, 'tech_data')->textarea(['rows' => 4]) ?>
					</div>
					<div class="col-sm-6">
						<?= $form->field($model, 'active')->dropDownList(['prompt' => 'Выберите статус', '1' => 'Опубликовано', '2' => 'Убрать с сайта']) ?>
						<?= $form->field($model, 'sales')->dropDownList(['prompt' => 'Выберите статус', '1' => 'SALES', '2' => 'Продано']) ?>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<div class="col-sm-6">
								<?= $form->field($upload, 'imageFile')->fileInput() ?>
							</div>
						</div>
					</div>
				</div>

				<div class="box-footer">
					<div class="form-btn">
						<?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
					</div>
				</div>

				<?php ActiveForm::end(); ?>

			</div>
		</div>

	</div>

views/dom/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\DomAdminSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="dom-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options'=>array('class'=>'form-inline')
    ]); ?>

<?= $form->field($model, 'id', [
                'template'=>'{input}<span class="input-group-btn"><button class="btn btn-warning btn-flat" type="submit"><i class="fa fa-search"></i></button></span>',
                'options'=>['class'=>'input-group input-group-sm']])
                ->textInput(['placeholder'=>Yii::t('app', 'Search')]);
            ?>

    <?php ActiveForm::end(); ?>

</div>

views/dom/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Dom */

$this->title = 'Создать Dom';
$this->params['breadcrumbs'][] = ['label' => 'Doms', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="dom-create">

    <?= $this->render('_form', [
        'model' => $model,
        'upload' => $upload,
    ]) ?>

</div>

views/dom/image.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Project */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="project-form">

    <div class="box box-default">

        <div class="box-body">
            <?php if (Yii::$app->user->can('admin') || Yii::$app->user->can('moder')): ?>
                <?php $form = ActiveForm::begin(); ?>
                <?= $form->field($model, 'id')->hiddenInput(['maxlength' => true])->label(false) ?>
                <?= $form->field($upload, 'files[]')->fileInput(['multiple' => true, 'accept' => 'image/*']) ?>

                <div class="box-footer">
                    <div class="form-btn">
                        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                    </div>
                </div>

                <?php ActiveForm::end(); ?>
            <?php endif;?>
            <?php if (!empty($photos)): ?>
                <div class="box-body">
                    <div id='gallery'>
                        <?php foreach ($photos as $photo): ?>
                            <a href="<?= Yii::getAlias('@web') . '/img/dom/' . $photo->idDom. '/' . $photo->path ?> "><img
                                    style="width: 240px" class="news-img"
                                    src="<?= Yii::getAlias('@web') . '/img/dom/' . $photo->idDom . '/cropped/' . $photo->path ?>"></a>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>

    </div>

views/dom/imagemore.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\DomAdminSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Добавить картинки';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="dom-index">

    <div class="box">

        <div class="box-header with-border">
            <div class="pull-left">
                <?= Html::a('Добавить дом', ['create'], ['class' => 'btn btn-success']) ?>
            </div>

        </div>

        <div class="box-body">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                //'filterModel' => $searchModel,
                'columns' => [
                    [
                        'attribute' => 'path',
                        'format' => 'html',
                        'label' => 'Фото',
                        'value' => function ($data) {
                            return '<img src=' . Yii::getAlias('@web') . '/img/dom/' . $data->idDom . '/cropped/' . $data->path . '>';
                        }
                    ],
//            ['class' => 'yii\grid\SerialColumn'],
//
//            'id',
//                    'tech_data',
//            'text:ntext',
//                    'avatarId',
//                    'price',
                    // 'material_house',
                    // 'material_roof',
                    // 'material_windows',
                    // 'material_doors',
                    // 'material_wall',
                    // 'area',
                    // 'eart',
                    // 'address',
                    // 'dop_info',
                    // 'geo_lat',
                    // 'geo_lng',
                    // 'post_adress',
                    // 'readiness',
                    // 'poverh',
//                    'active',

                    [
                        'class' => 'yii\grid\ActionColumn',
                        'headerOptions' => ['width' => '70'],
                        'template' => '{view} {update}  {delete}{image}',


                        'buttons' => [
                            'image' => function ($url) {
                                return Html::a('<span class="glyphicon glyphicon-picture"></span>', $url, [
                                    'title' => Yii::t('app', 'Work'),
                                ]);
                            },
                        ],
                        'urlCreator' => function ($action, $model, $key, $index) {
                            switch($action){
                                case 'update':
                                    $url = \yii\helpers\Url::toRoute(['dom-image/update','id'=>$model->id]);
                                    return $url;
                                case 'view':
                                    $url = \yii\helpers\Url::toRoute(['dom-image/view','id'=>$model->id]);
                                    return $url;
                                case 'delete':
                                    $url = \yii\helpers\Url::toRoute(['dom-image/delete','id'=>$model->id]);
                                    return $url;
                                case 'image':
                                    $url = \yii\helpers\Url::toRoute(['dom-image/view','id'=>$model->id]);
                                    return $url;
                            }
                        }
                    ],
                ],
            ]); ?>
        </div>

    </div> <!--end box -->

</div>

views/dom/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\DomAdminSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Администратор Domsovinyon';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="dom-index">

    <div class="box">

        <div class="box-header with-border">
            <div class="pull-left">
                <?= Html::a('Добавить дом', ['create'], ['class' => 'btn btn-success']) ?>
            </div>

        </div>

        <div class="box-body">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                //'filterModel' => $searchModel,
                'columns' => [
                    [
                        'attribute' => 'avatar_id',
                        'format' => 'html',
                        'label' => 'Фото',
                        'value' => function ($data) {
                            return '<img class="img-responsive" src=' . Yii::getAlias('@web') . '/img/dom/' . $data->id . '/cropped/f_' . $data->avatar->path . ' alt="foto house">';
                        }
                    ],
//            ['class' => 'yii\grid\SerialColumn'],
//
//            'id',
                    'tech_data',
//            'text:ntext',
//                    'avatarId',
                    'price',

                    [
                        'attribute' => 'active',
                        'value' => function($data){
                            switch ($data->active){
                                case 1: return 'Активна';
                                case 2: return 'Черновик';
                                default: return '';
                            }

                        }
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'headerOptions' => ['width' => '70'],
                        'template' => '{view} {update}  {delete}{image}',


                        'buttons' => [
                            'image' => function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-picture"></span>', $url, [
                                    'title' => Yii::t('app', 'Work'),
                                ]);
                            },
                        ],
                        'urlCreator' => function ($action, $model, $key, $index) {
                            switch($action){

                                case 'update':
                                    $url = \yii\helpers\Url::toRoute(['dom/update','id'=>$model->id]);
                                    return $url;
                                case 'view':
                                    $url = \yii\helpers\Url::toRoute(['dom/view','id'=>$model->id]);
                                    return $url;
                                case 'delete':
                                    $url = \yii\helpers\Url::toRoute(['dom/delete','id'=>$model->id]);
                                    return $url;
                                case 'image':
                                    $url = \yii\helpers\Url::toRoute(['dom/imagemore','id'=>$model->id]);
                                    return $url;
                            }
                        }
                    ],
                ],
            ]); ?>
        </div>

    </div> <!--end box -->

</div>

views/dom/moremaps.php
<?php

use dosamigos\google\maps\LatLng;
use dosamigos\google\maps\services\DirectionsWayPoint;
use dosamigos\google\maps\services\TravelMode;
use dosamigos\google\maps\overlays\PolylineOptions;
use dosamigos\google\maps\services\DirectionsRenderer;
use dosamigos\google\maps\services\DirectionsService;
use dosamigos\google\maps\overlays\InfoWindow;
use dosamigos\google\maps\overlays\Marker;
use dosamigos\google\maps\Map;
use dosamigos\google\maps\services\DirectionsRequest;
use dosamigos\google\maps\overlays\Polygon;
use dosamigos\google\maps\layers\BicyclingLayer;

$coord = new LatLng(['lat' => $lat, 'lng' => $lng]);
$map = new Map([
    'center' => $coord,
    'zoom' => 19,
    'width' => '100%',
    'height' => '100%',
]);

// Позволяет добавить маркер в настоящее время
$marker = new Marker([
    'position' => $coord,
    'title' => 'Офис продаж',
]);

// Обеспечить общий InfoWindow к маркеру
$marker->attachInfoWindow(
    new InfoWindow([
        'content' => '<p>Отличный дом для добрых людей!</p>'
    ])
);

// Добавить маркер на карте
$map->addOverlay($marker);

// Отображение карты
echo $map->display();

views/dom/update.php
<?php


/* @var $this yii\web\View */
/* @var $model app\models\Dom */

$this->title = 'Редактировать Dom' . ' #' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Dom', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Обновить';
?>
<div class="container">
    <div class="row">
        <div class="dom-update col-sm-12">
            <div class="col-sm-11 col-sm-ofset-1">
                <div class="alert alert-info">Информация про ДОМ</div>
                <?= $this->render('_form', [
                    'model' => $model,
                    'upload' =>$upload,
                ]) ?>
            </div>
        </div>
    </div>
    </div>